# Generated by Django 5.2.4 on 2025-08-11 04:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('start_year', models.PositiveIntegerField(help_text='Year when the project starts (e.g., 2025)')),
                ('start_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month when the project starts (1–12)')),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Year when the project ends (leave blank if ongoing)', null=True)),
                ('end_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month when the project ends (leave blank if ongoing)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete toggle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['project_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('REGULAR', 'Regular Project'), ('FIXED_COST', 'Fixed Cost Project')], default='REGULAR', max_length=20)),
                ('year', models.PositiveIntegerField(help_text='Year for this report (e.g., 2025)')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month for this report (1–12)')),
                ('present_day', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('billable_days', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('non_billable_days', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('billable_hours', models.FloatField(default=0, editable=False)),
                ('non_billable_hours', models.FloatField(default=0, editable=False)),
                ('extra_hours', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('counting', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poc', models.ManyToManyField(blank=True, related_name='poc_projects', to='resources.resource')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
                ('project_profile', models.ForeignKey(help_text='Main profile/resource for this project', on_delete=django.db.models.deletion.PROTECT, related_name='profiled_projects', to='resources.resource')),
                ('resources', models.ManyToManyField(blank=True, related_name='assigned_projects', to='resources.resource')),
            ],
            options={
                'db_table': 'project_reports',
                'ordering': ['-year', '-month', 'project__project_name'],
            },
        ),
    ]
