# Generated by Django 5.2.4 on 2025-08-03 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_counting'),
        ('resources', '0002_remove_resource_updated_at_resource_counting'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_profile',
            field=models.ForeignKey(default=1, help_text='Main profile/resource for this project', on_delete=django.db.models.deletion.PROTECT, related_name='profiled_projects', to='resources.resource'),
            preserve_default=False,
        ),
    ]
