# Generated by Django 5.2.4 on 2025-08-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
    ]
