# Generated by Django 5.2.4 on 2025-08-06 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_unique_together'),
        ('resources', '0003_resource_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_hours',
            field=models.FloatField(blank=True, help_text='Any additional hours (optional)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_profile',
        ),
        migrations.AddField(
            model_name='project',
            name='project_profile',
            field=models.ManyToManyField(help_text='Main profiles/resources for this project', related_name='profiled_projects', to='resources.resource'),
        ),
    ]
