# Generated by Django 5.2.4 on 2025-08-06 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_extra_hours_remove_project_project_profile_and_more'),
        ('resources', '0003_resource_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_profile',
        ),
        migrations.AddField(
            model_name='project',
            name='project_profile',
            field=models.ForeignKey(default=1, help_text='Main profile/resource for this project', on_delete=django.db.models.deletion.PROTECT, related_name='profiled_projects', to='resources.resource'),
            preserve_default=False,
        ),
    ]
