# Generated by Django 5.2.4 on 2025-08-06 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_project_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='extra_hours',
            field=models.FloatField(blank=True, default=0, help_text='Any additional hours (optional)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
