# Generated by Django 5.2.4 on 2025-08-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_extra_hours'),
        ('resources', '0003_resource_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='poc',
            field=models.ManyToManyField(blank=True, help_text='Multiple POCs can be assigned to this project', related_name='poc_projects', to='resources.resource'),
        ),
    ]
