# Generated by Django 5.2.4 on 2025-08-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_poc'),
        ('resources', '0003_resource_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='resources',
            field=models.ManyToManyField(blank=True, help_text='Multiple resources can be assigned to this project', related_name='assigned_projects', to='resources.resource'),
        ),
    ]
