# Generated by Django 5.2.4 on 2025-08-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='task_description',
            field=models.TextField(blank=True, help_text='Description of the task assigned to the intern', null=True),
        ),
    ]
