# Generated by Django 4.2.23 on 2025-08-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
