# Generated by Django 4.2.23 on 2025-09-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_intern_month_intern_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='convert_to_resource',
            field=models.BooleanField(default=False),
        ),
    ]
