# Generated by Django 5.2.4 on 2025-08-11 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(help_text='Full name of the resource', max_length=100, unique=True)),
                ('join_date', models.DateField(help_text='Date the resource joined')),
                ('leave_date', models.DateField(blank=True, help_text='Date the resource left (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Mark inactive if resource left')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'db_table': 'resources',
                'ordering': ['resource_name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceMonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('working_days', models.FloatField(blank=True, help_text='Leave blank to auto-calculate (Mon-Fri + 1st Saturday)', null=True)),
                ('present_day', models.FloatField(default=0)),
                ('present_hours', models.FloatField(default=0)),
                ('counting', models.FloatField(default=0, help_text='Custom counting value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_data', to='resources.resource')),
            ],
            options={
                'db_table': 'resource_monthly_data',
                'ordering': ['-year', '-month', 'resource'],
                'unique_together': {('resource', 'year', 'month')},
            },
        ),
    ]
