# Generated by Django 5.2.4 on 2025-08-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcemonthlydata',
            name='counting',
        ),
    ]
