# Generated by Django 5.2.4 on 2025-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="resource",
            name="counting",
            field=models.FloatField(default=0, help_text="Counting value"),
        ),
    ]
