# Generated by Django 4.2.23 on 2025-08-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resourcemonthlydata_counting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcemonthlydata',
            unique_together=set(),
        ),
    ]
