# Generated by Django 5.2.4 on 2025-08-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_updated_at_resource_counting'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to deactivate this resource instead of deleting.'),
        ),
    ]
