# Generated by Django 4.2.23 on 2025-08-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resourcemonthlydata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcemonthlydata',
            name='working_days',
            field=models.FloatField(blank=True, default=0, help_text='Leave blank to auto-calculate (Mon-Fri + 1st Saturday)', null=True),
        ),
    ]
