# Generated by Django 5.2.4 on 2025-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Enter the month manually (1-12)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='present_hours',
            field=models.FloatField(default=0, help_text='Auto-calculated as present_day * 8 hours if not set'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='working_days',
            field=models.FloatField(blank=True, help_text='Leave blank to auto-calculate (Mon-Fri + 1st Saturday)', null=True),
        ),
    ]
