# Generated by Django 5.2.4 on 2025-08-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resource_month_alter_resource_present_hours_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set(),
        ),
    ]
